version: 2
jobs:
  build_front:
    steps:
      - run: npm install
      # - run: npm run deploy

  api_test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.4.2-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake db:create db:schema:load db:migrate
      - run:
          name: Run request specs
          command: bundle exec rspec spec/requests
      - run:
          name: Run model specs
          command: bundle exec rspec spec/models

  deploy_staging:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git staging
      - run:
          name: Migrate DB
          command: |
            heroku run rake db:migrate --app $HEROKU_APP_NAME
      - run:
          name: Restart the app
          command: |
            heroku restart --app $HEROKU_APP_NAME

  deploy_master:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Migrate DB
          command: |
            heroku run rake db:migrate --app $HEROKU_APP_NAME
      - run:
          name: Restart the app
          command: |
            heroku restart --app $HEROKU_APP_NAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - api_test
      - build_front
      - deploy_staging:
          requires:
            - api_test
          filters:
            branches:
              only: staging
      - deploy_master:
          requires:
            - api_test
          filters:
            branches:
              only: master
